### ISSUE TITLE
Create a profile 

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#1]
**DESCRIPTION:**
When I navigate to the registration page, I am presented with two options for creating my profile. The first option allows me to enter my basic information, including my name, email address, and password, to create an account on the platform. The second option allows me to sign up with my Google account, which will pre-fill some of my profile information using the data from my Google account (such as name and profile picture).
Once I choose my way of signing up, I am redirected to the profile creation page. Here, I am presented with the option to add additional information about myself. I can choose to complete all of these sections at once or return to the profile creation page later to add more information.
Upon completion of my profile, I can start using the platform as a member.

**ACCEPTANCE CRITERIA:** 

- Given a user who wants to create a profile,
When the user accesses the platform's homepage,
Then the user should be able to access the registration page.
- Given a user who wants to create a profile,
When the user accesses the registration page,
Then the user should see two options for creating a profile: entering basic information or signing up with a Google account.
- Given a user who has completed their profile,
When the user accesses their profile page,
Then the user should be able to view their profile, edit it, and the information should be accurate and displayed correctly.

**Comment by MomooDiane** [comment]
was completed in #31
