### ISSUE TITLE
Store documents.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#10]
**DESCRIPTION**

As a user, I want to store personal documents (such as resume and cover letter) so that I can easily access them when applying for jobs.

When I log in to the platform, I should be able to navigate to a section where I can upload and store my important job search documents. 

**ACCEPTANCE CRITERIA**

- Given that the user has accessed their profile page,
When they navigate to the "Documents" section,
Then they should be able to upload and store important documents such as their resume and cover letter, as well as any other relevant files.
- Given that the user has uploaded important documents to their profile,
When they view their profile page,
Then they should be able to see a section displaying their uploaded documents, along with the ability to download or remove them.

**Comment by MomooDiane** [comment]
was completed in #52
