### ISSUE TITLE
Post external jobs.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#13]
**DESCRIPTION**

As a recruiter, I want to post jobs hosted on third party platforms so that users can find/apply to external offers.

When I log in to the platform as a recruiter, In the job posting section, I should be able to post external job offers as links. 
If I choose to post an external job offer, I should be able to provide a link to the original job posting on the third party platform. The link should be clickable and take users directly to the external job posting.

**ACCEPTANCE CRITERIA**
- Given a recruiter has an account on the platform and is logged in
When the recruiter navigates to the job postings section
And selects the option to post an external job offer
Then the recruiter should be able to provide the job title and post the job’s link.

**Comment by TNT05** [comment]
closed in #67
