### ISSUE TITLE
Create/Join groups.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#14]
**DESCRIPTION**
As a user, I want to create groups and invite others to my group so that I connect and communicate with like-minded individuals.

When I create a group, I should be able to choose the name and description of the group.
Once the group is created, I should be able to invite other users to the group.

**ACCEPTANCE CRITERIA**

- Given that I am logged in,
When I am a member of a group,
Then I should be able to see all the content of the group.

**Comment by MomooDiane** [comment]
Completed in #125 and #129
