### ISSUE TITLE
View notifications.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#15]
**DESCRIPTION**
As a user, I want to have a notification section so that I view all recent activities.

When I log into the platform, I should be able to access the notification section. In the notification section, I should be able to view a list of all recent notifications, including notifications such as connection requests or job posting updates.

**ACCEPTANCE CRITERIA**

- Given that I am logged in,
When I navigate to the notification icon or link,
Then I should be directed to the notification section.

**Comment by drbladz** [comment]
Completed in #138
