### ISSUE TITLE
Save items.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#18]
**DESCRIPTION**
As a user, I want to save posts, jobs and events so that I can access and refer back to them later.

When I see a post or job offer that I want to save, I should be able to click a "save" button to add it to my saved items list.
From the menu, I should be able to access my list of saved items and see all the items I have saved. For each item, I should be able to see its title, a brief summary or description, and be able to click it to view the full item.
I should also be able to remove items from my saved list.

**ACCEPTANCE CRITERIA**

- Given a user is logged in and viewing content on the platform
When the user wants to save a post, job offer, or other content
Then the user should be able to click a "Save" button to add the content to their saved items list
the saved items list should be easily accessible from the main navigation menu
the user should be able to view and manage their saved items list, including deleting items

**Comment by TNT05** [comment]
closed with #126
