### ISSUE TITLE
Invite other users to network.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#23]
Substory of #2 
**DESCRIPTION**
 As a user, I want to send an invitation to a user so that I can expand my network on the platform.

When I visit another user's profile, I should be able to click a button in order to send a network request to that user. 
When I send a request, the receiving user should have the option to accept or reject it. If the user accepts my request, we should both be added to each other's network, and we should be able to view each other's profiles and any posts or content that we share on the platform.

**ACCEPTANCE CRITERIA**
- Given a user who is visiting another user's profile,
When the user views the profile,
Then there should be a button that allows the user to send a connection request.
- Given a user who receives a connection request,
When the user receives the request notification,
Then the user should have the option to accept or reject the request.

**Comment by drbladz** [comment]
Completed in #57
