### ISSUE TITLE
Respond to invitation.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#24]
Substory of #2 
**DESCRIPTION**
As a user, I want to accept, reject or ignore other users invitations, so that I can accept or decline the request and manage my network of connections on the platform.

When I receive a connection request from another user, I should receive a notification that indicates the invitation.
From the notification, I should be able to navigate to a page or section of the platform that allows me to view the connection request and either accept or decline the request. If I choose to accept the request, the user who sent the request should be added to my network.
I should be able to view all my pending connection requests. I should be able to manage each request by accepting or declining the request.

**ACCEPTANCE CRITERIA**
- Given a user who has received a connection request,
When the user navigates to connections section of the platform,
Then the user should be able to view the connection request.
- Given a user who has received a connection request,
When the user views the connection request,
Then the user should be able to either accept or decline the request.
- Given a user who has accepted a connection request,
Then the inviting user should be added to the receiving user's network.

**Comment by chloehylaw** [comment]
Duplicate issue from story #3
