### ISSUE TITLE
Remove connections.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#25]
Substory of #2 
**DESCRIPTION**
As a user, I want to remove connections so that I can manage my network and maintain connections that are relevant to me.

In my connections section, I should be able to see a list of all the users I'm currently connected with.  I should be able to see an option to remove the connection with a user.
I should also be able to remove connection with a user directly from their profile.

**ACCEPTANCE CRITERIA**
- Given a user who is logged in to the platform,
When the user goes to connections section,
Then the user should be able to view a list of all their current connections.
- Given a user is viewing their connections list,
When the user selects a connection from the list,
Then the user should be presented with an option to remove the connection.

**Comment by drbladz** [comment]
Completed in #57
