### ISSUE TITLE
Create a new group.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#29]
Substory of #14 
**DESCRIPTION**
As a user, I want to be able to create a new group so that I can connect with other users who share common interests or goals.

**ACCEPTANCE CRITERIA**

- Given a user is logged in
When the user navigates to the Groups section
Then the user should be able to create a new group by providing a name, and description.
- Given a user is logged in
when the user is a group owner/admin
Then the user should be able to invite others to his group

**Comment by MomooDiane** [comment]
Completed in #125 and #129

**Comment by MomooDiane** [comment]
Completed in #125 and #129
