### ISSUE TITLE
Respond to invitation

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#3]
**DESCRIPTION**

When I receive a connection request from another user, I should receive a notification that indicates the invitation.
From the notification, I should be able to navigate to a page or section of the platform that allows me to view the connection request and either accept or decline the request. If I choose to accept the request, the user who sent the request should be added to my network.
I should be able to view all my pending connection requests and manage each request by accepting or declining the request.

**ACCEPTANCE CRITERIA**

-Given a user who has received a connection request,
When the user navigates to the connections section of the platform,
Then the user should be able to view the connection request.
-Given a user who has received a connection request,
When the user views the connection request,
Then the user should be able to either accept or decline the request.
-Given a user who has accepted a connection request,
Then the inviting user should be added to the receiving user's network.

**Comment by drbladz** [comment]
Completed in #57
