### ISSUE TITLE
Join a group.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#30]
Substory of #14
**DESCRIPTION**

As a user, I want to be able to join groups, so that I can engage with other users who share similar interests or backgrounds.

**ACCEPTANCE CRITERIA**

- Given that I am logged in, 
when I search for groups on the platform, 
Then I should be able to see a list of available groups that I can join.
When I click on a group from the list, 
Then the platform should display relevant information about the group, such as the group description, rules, and current members.
I should be able to click a button to join the group.

**Comment by MomooDiane** [comment]
Completed in #125 and #129
