### ISSUE TITLE
Edit profile

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#32]
**DESCRIPTION**

As a user, I want to be able to manage and edit my profile so that I can keep my profile updated.
When I want to edit my profile, I should be able to access and edit various sections of my profile, such as my profile picture, bio, contact information, education, and work experience, interests, and private settings. 
By being able to manage and edit my profile, I can present myself in the best possible light to other users and increase my chances of building meaningful connections and relationships

**ACCEPTANCE CRITERIA**

- Given a user is logged in to a social media platform or community website
When they navigate to their profile page
Then they should be able to view and edit various sections of their profile, such as their profile picture, bio, contact information, education and work experience, interests, and privacy settings
And they should be able to save their changes and see the updated information reflected on their profile page
And they should be able to undo or revert any changes made to their profile if needed

**Comment by chloehylaw** [comment]
Created user substory for this

**Comment by chloehylaw** [comment]
Duplicate

**Comment by MomooDiane** [comment]
was completed in #31
