### ISSUE TITLE
Add a personal summary

### ISSUE THREAD

**Issue by chloehylaw** [TNT05/MiniCap#35]
SUBSTORY OF #1 Create a profile

As a user, I want to be able to provide a brief summary of myself so that other users can quickly understand my professional interests and goals

DESCRIPTION
When I create my profile, I should be able to add a brief summary of myself, highlighting my professional interests, goals, and achievements.

ACCEPTANCE CRITERIA
Given a user who has created their profile,
When they add a summary about themselves,
Then the information should be displayed on their profile.

**Comment by MomooDiane** [comment]
was completed in #31
