### ISSUE TITLE
Add educational details

### ISSUE THREAD

**Issue by chloehylaw** [TNT05/MiniCap#36]
SUBSTORY OF #1 Create a profile

As a user, I want to be able to add my educational details, so that potential employers can see my academic background.

DESCRIPTION
When I create my profile, I should be able to add my educational details, including my degree(s) earned, field(s) of study, school name(s), and dates attended.

ACCEPTANCE CRITERIA
Given a user who has created their profile,
When they add their education details,
Then the information should be displayed on their profile under the education section.

**Comment by MomooDiane** [comment]
was completed in #31
