### ISSUE TITLE
Add work experience

### ISSUE THREAD

**Issue by chloehylaw** [TNT05/MiniCap#37]
SUBSTORY OF #1 Create a profile

As a user, I want to be able to add my work experience to my profile, so that others can see my professional background.

DESCRIPTION
When I navigate to the experience section of my profile, I should be able to click on an "Add Experience" button and enter the following information: job title, company name, employment type (full-time, part-time, contract), location, start and end dates, job description, and any relevant media.

ACCEPTANCE CRITERIA
Given a user who has complete their profile,
When the user accesses their experience section,
Then the user should be able to view their experience section, edit it, and the information should be accurate and displayed correctly.

**Comment by MomooDiane** [comment]
was completed in #31
