### ISSUE TITLE
Add skills and achievements

### ISSUE THREAD

**Issue by chloehylaw** [TNT05/MiniCap#38]
SUBSTORY OF #1 Create a profile

As a user, I want to be able to showcase my skills and achievements, so that potential employers can see my strengths and accomplishments

DESCRIPTION
When I create my profile, I should be able to add my skills and achievements, including specific projects I've worked on, certifications I've earned, and awards I've received.

ACCEPTANCE CRITERIA
Given a user who has completed their profile,
When they add their skills and achievements,
Then the information should be displayed on their profile correctly.

**Comment by MomooDiane** [comment]
was completed in #31
