### ISSUE TITLE
Change profile picture

### ISSUE THREAD

**Issue by chloehylaw** [TNT05/MiniCap#39]
SUBSTORY OF #1 Create a profile

As a user I want to be able to upload a new profile picture from my computer and reflect the change on my profile

DESCRIPTION
When I navigate to my profile page, I should see an option to edit my profile picture by uploading a new image from my device or choose from existing images in my account.

ACCEPTANCE CRITERIA
"Given a user who is logged into their profile,
When they navigate to their profile page and select the option to upload a new image
Then they should be able to choose an image from their device and upload it successfully."

**Comment by MomooDiane** [comment]
was completed in #49
