### ISSUE TITLE
Create job posting

### ISSUE THREAD

**Issue by chloehylaw** [TNT05/MiniCap#40]
SUBSTORY OF #8 Post job offers

As a recruiter, I want to be able to create job postings, so that I can attract qualified candidates for open positions.

DESCRIPTION
When I navigate to the post the job section of the platform, I should be able to create a new job posting by filling out a form with details such as job title, description requirements, and compensation.

ACCEPTANCE CRITERIA
Given a recruiter who navigates to the post a job section,
When they fill out the form with all the required details and submit the job postins,
Then the job should be added to the platform's job board and visible to job seekers.

**Comment by TNT05** [comment]
closed in #33
