### ISSUE TITLE
Create a company page

### ISSUE THREAD

**Issue by chloehylaw** [TNT05/MiniCap#41]
SUBSTORY OF #16 Create a page

As a company owner, I want to be able to create a company page, so that I can showcase my company to potential customers and employees.

DESCRIPTION
When I navigate to the create a page section of the platform, I should be able to create a new company page by filling out a form with details such as company name, logo, description, industry, and website.

ACCEPTANCE CRITERIA
Given a company owner who navigates to the create a page section of the platform,
When they fill out the form with all the required details and submit the page
Then the page should be added to the platform's page directory and visible to users.

**Comment by OussamaJmili** [comment]
Completed in #135
