### ISSUE TITLE
Sign up page

### ISSUE THREAD

**Issue by chloehylaw** [TNT05/MiniCap#43]
As a new user, I want to be able to create a new account so that I can use the platform and access its features.

DESCRIPTION
When I visit the homepage of the website, I should see a "Signup" button. Upon clicking on the link, I should be taken to a registration page where I can enter my email address, create a password, and fill out my profile information.

ACCEPTANCE CRITERIA
"Given that I am on the homepage, 
When I click on the sign up button,
Then I should be taken to the registration page."

**Comment by TNT05** [comment]
closed in #22   #21
