### ISSUE TITLE
Sign in page

### ISSUE THREAD

**Issue by chloehylaw** [TNT05/MiniCap#44]
As a registered user, I want to be able to sign in to my account, so that I can access my personalized dashboard and network with other users.

DESCRIPTION
When I visit the website, I should see a "sign in" button. Upon clicking on the link, I should be taken to a login page where I can enter my email address and password to access my account.

ACCEPTANCE CRITERIA
"Given that I am on the homepage, 
When I click on the sign in button,
THen I should be taken to the login page.

Given that I am on the login page, 
When I enter my valid email address and password, 
Then I should be able to submit the form.

GIven that my email and password are correct, 
When my login is successful, 
Then I should be redirected to my dashboard."

**Comment by TNT05** [comment]
closed in #22  #21
