### ISSUE TITLE
Logout page

### ISSUE THREAD

**Issue by chloehylaw** [TNT05/MiniCap#45]
As a logged-in user, I want to be able to logout of my account, so that my personal information and account details are secure.

DESCRIPTION
When I am logged into my account, I should see a logout button. Upon clicking on it, I should be logged out of the platform and taken to the homepage.

ACCEPTANCE CRITERIA
"Given that I am logged into my account, 
When I click on the logout button, 
Then i should be logged out of my platform and taken to the homepage."

**Comment by TNT05** [comment]
closed in #22  #21
