### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by chloehylaw** [TNT05/MiniCap#46]
As a user, I want to be able to see a clear, informative and personalized homepage, so that I can learn more about the website, its features and quickly access to relevant information.

DESCRIPTION
When I visit the website, I should be presented with a homepage with clear, informative, visually appealing, and personalized interests and activities. The homepage should include relevant information such as recent activity, news, updates, job postings, and suggested connections. 

ACCEPTANCE CRITERIA 
"Given a user logged into the account, 
When I visit the homepage,
Then I should see information and updates relevant to my interests and activity on the website."

**Comment by TNT05** [comment]
closed in #22  #21
