### ISSUE TITLE
Dashboard page

### ISSUE THREAD

**Issue by chloehylaw** [TNT05/MiniCap#47]
As a user, I want to be able to see an informative dashboard, so that I can easily access my profile, connections, and activity on the website.

DESCRIPTION
When A user logs into their account, they should be presented with a dashboard that is clear, informative, visually appealing. The dashboard should include relevant information and be easy to navigate.

ACCEPTANCE CRITERIA
"Given a user logged into their account,
When the user lands on the dashboard page,
Then the user should be able to navigate it and find the relevant information and features necessary."

**Comment by TNT05** [comment]
closed in #22  #21
