### ISSUE TITLE
Directly message users.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#5]
**DESCRIPTION**

When I navigate to the messaging section of the platform, I should be able to see a list of all my previous conversations and any unread messages. From there, I should be able to start a new conversation with another user by clicking on their name.
I should also be able to start a private message with a user from their profile if they are in my network.

**ACCEPTANCE CRITERIA**

- Given a user who is logged in to the platform,
When the user clicks on another user's name or username from the messaging section or clicks the message button from their profile,
Then the user should be able to start a new conversation with the other user.
- Given a user who receives a new message,
Then the user should receive a notification that they have a new message.
- Given a user who is engaged in a conversation,
When the user views the conversation,
Then the user should be able to see the status of each message (read, unread).
- Given a user who is logged in,
When the user needs to report a user,
Then the messaging system should have the necessary features to allow the user to report other users.
- Given a user who is using the messaging system,
When the user needs to manage their conversations,
Then the messaging system should have features to allow the user to easily delete conversations.

**Comment by TNT05** [comment]
closed in #79
