### ISSUE TITLE
Delete job application (as a recruiter)

### ISSUE THREAD

**Issue by chloehylaw** [TNT05/MiniCap#50]
SUBSTORY OF #8 Post job offers

As a recruiter, I want to delete a job application from a candidate so that I can manage my job postings efficiently and keep my recruitment pipeline up to date.

DESCRIPTION
When I am viewing my job dashboard and see an application I want to remove, I should be able to click on a "delete" button to initiate the deletion process. A confirmation pop-up should appear to ensure that I am certain about deleting the application.

ACCEPTANCE CRITERIA
"Given that I am a recruiter,
When I am viewing my job dashboard
Then I shoule be able to see a list of all job applications that have been submitted for my job postings.

Given that I am viewing the job application list, 
When I click on the delete button, 
Then the job applicaiton should be permanently deleted from the system."

**Comment by OussamaJmili** [comment]
Feature not planned for now
