### ISSUE TITLE
Recruiter Job Postings Dashboard.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#53]
As a recruiter, I want to be able to view a section where I can see all of my job postings in one place.

**DESCRIPTION**

 This will allow me to easily keep track of the job postings I have created and see how many applications each job has received. Additionally, I can quickly access and edit any job posting that needs to be updated or modified. With this feature, I can save time and stay organized by having all of my job postings easily accessible from one central location.
 
 **ACCEPTANCE CRITERIA**
* Given a recruiter has created multiple job postings on the platform,
When the recruiter navigates to the "My Job Postings" page,
Then they should see a list of all their job postings displayed on the page,
And each job posting should display the title, date created, and the number of applications received.

**Comment by TNT05** [comment]
closed in #51
