### ISSUE TITLE
Share files.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#6]
Substory of #5 
**DESCRIPTION**

In a direct message conversation with another user, I should be able to attach different types of files to my message, including documents, images, and videos. The platform should support a range of common file formats, and the maximum file size for each attachment should be clearly stated.
When I select a file to attach to my message, I should be able to preview the file to ensure that I have selected the correct file. 
When the other user receives my message, they should be able to view the attached files and download them if necessary.

**ACCEPTANCE CRITERIA**

- The user should be able to attach different types of files to direct messages.
When the user selects a file to attach to their message, they should be able to preview the file to ensure that it is the correct file.

**Comment by drbladz** [comment]
Completed in #118
