### ISSUE TITLE
Moderate direct messages.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#7]
**DESCRIPTION**
As an admin, when I log in to the platform, I should be able to view a list of all direct message conversations that have been reported by users.

**ACCEPTANCE CRITERIA**

- Given that the platform has a reporting system for users to report conversations violating policies,
When a moderator accesses the reported conversations section,
Then the platform should display all reported conversations.

**Comment by TNT05** [comment]
closed in #112 #121
