### ISSUE TITLE
Post job offers.

### ISSUE THREAD

**Issue by OussamaJmili** [TNT05/MiniCap#8]
**DESCRIPTION**
As a recruiter, when I want to post a job offer, I should be able to access a job posting form. The form should include fields for job titles, job descriptions, required qualifications, salary ranges, and other information about the position.

**ACCEPTANCE CRITERIA**

- Given a recruiter is logged in to the platform,
When they press the job posting button,
Then they should be able to input all required job details including job title, job description, qualifications, compensation, location, and application instructions.
- Given a recruiter is logged in to the platform,
When they navigate to their past job postings,
Then they should be able to view a list of all their existing job postings and have the ability to edit or delete them as needed.
- Given a recruiter is logged in to the platform,
When they navigate to a specific job posting,
Then they should be able to view a list of all applicants who have submitted applications for that job with their profile.

**Comment by TNT05** [comment]
closed in #33  #34  #48  #51  #55  #54
